name: glybot

services:

  qdrant_vector_db:
      image: qdrant/qdrant:latest
      ports:
        - "6333:6333"
        - "6334:6334"

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8501:8501"
    depends_on:
      - qdrant_vector_db
    links:
      - qdrant_vector_db