name: glybot

services:

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8501:8501"

  qdrant_vector_db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/data