name: glybot

services:

  qdrant_vector_db:
    build: qdrant
    # volumes:
    #   - ./storage:/qdrant/storage

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    # user: 1000:100
    ports: 
      - "8501:8501"
    depends_on:
      - qdrant_vector_db
    links:
      - qdrant_vector_db
